Acme\DemoBundle\Model\TodoCollection:
  exclusion_policy: ALL
  xml_root_name: todos
  properties:
    todos:
      expose: true
      type: array<Acme\DemoBundle\Model\Todo>
      xml_list:
        inline: true
        entry_name: todo
    offset:
      expose: true
      type: integer
      xml_attribute: true
    limit:
      expose: true
      type: integer
      xml_attribute: true
  relations:
    -
      rel: self
      href:
        route: get_todos
        absolute: true
    -
      rel: todo
      href:
        route: get_todo
        absolute: true
        generator: templated_uri
        parameters:
          id: "{id}"
      attributes:
        templated: true
